using Microsoft.EntityFrameworkCore.Migrations;
using RSoft.Person.Infra.Tables;
using System;
using System.Diagnostics.CodeAnalysis;

namespace RSoft.Person.Infra.Migrations
{

    /// <summary>
    /// Initial seed data migration
    /// </summary>
    [ExcludeFromCodeCoverage(Justification = "Migrations are automatically generated by .net")]
    public abstract class InitialSeed : Migration
    {

        /// <summary>
        /// Seed initial data
        /// </summary>
        /// <param name="migrationBuilder">A MicrationBuilder object instance</param>
#pragma warning disable CA1822 // Mark members as static
        protected void Seed(MigrationBuilder migrationBuilder)
        {

            Guid userId = new("d2401226-754a-4535-85bc-6a3e559da66d");
            Guid serviceId = new("4d6016b8-9a70-434c-96ab-35a94824b6db");

            migrationBuilder.Sql("set foreign_key_checks=0");

            migrationBuilder.InsertData
            (
                nameof(User),
                new string[]
                {
                    nameof(User.Id),
                    nameof(User.FirstName),
                    nameof(User.LastName),
                    nameof(User.IsActive)
                },
                new object[] { userId, "Admin", "RSoft", true }
            );

            migrationBuilder.InsertData
            (
                nameof(User),
                new string[]
                {
                    nameof(User.Id),
                    nameof(User.FirstName),
                    nameof(User.LastName),
                    nameof(User.IsActive)
                },
                new object[] { serviceId, "Person", "Service", true }
            );

            migrationBuilder.Sql("set foreign_key_checks=1");

        }
#pragma warning restore CA1822 // Mark members as static


    }
}
