// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSoft.Person.Infra;

#nullable disable

namespace RSoft.Person.Infra.Migrations
{
    [DbContext(typeof(PersonContext))]
    [Migration("20230704104706_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RSoft.Person.Infra.Tables.AddressType", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<int>("Description")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("int")
                        .HasColumnName("Description");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasDatabaseName("AK_AddressType_Description");

                    b.ToTable("AddressType", (string)null);
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2000)")
                        .HasColumnName("Note");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_Person_ChangedBy");

                    b.HasIndex("ChangedOn")
                        .HasDatabaseName("IX_Person_ChangedOn");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Person_CreatedBy");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_Person_CreatedOn");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_Person_FullName");

                    b.ToTable("Person", (string)null);
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.PersonAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("AddressNumber");

                    b.Property<byte>("AddressTypeId")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("AddressTypeId");

                    b.Property<string>("City")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("City");

                    b.Property<string>("District")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("District");

                    b.Property<Guid?>("PersonId")
                        .IsRequired()
                        .HasColumnType("char(36)")
                        .HasColumnName("PersonId");

                    b.Property<string>("SecondaryAddress")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("SecondaryAddress");

                    b.Property<string>("State")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("State");

                    b.Property<string>("StreetName")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)")
                        .HasColumnName("StreetName");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Title");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("ZipCode");

                    b.HasKey("Id");

                    b.HasIndex("AddressTypeId")
                        .HasDatabaseName("IX_PersonAddress_AddressTypeId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_PersonAddress_PersonId");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("AK_PersonAddress_Title");

                    b.ToTable("PersonAddress", (string)null);
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.PersonPhone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CityCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CityCode");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CountryCode");

                    b.Property<ulong>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul)
                        .HasColumnName("IsDefault");

                    b.Property<Guid?>("PersonId")
                        .IsRequired()
                        .HasColumnType("char(36)")
                        .HasColumnName("PersonId");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("PhoneNumber");

                    b.Property<int>("PhoneType")
                        .HasColumnType("int")
                        .HasColumnName("PhoneType");

                    b.HasKey("Id");

                    b.HasIndex("PersonId", "CountryCode", "CityCode", "PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("AK_PersonPhone_Person_FullPhoneNumber");

                    b.ToTable("PersonPhone", (string)null);
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.PersonType", b =>
                {
                    b.Property<Guid?>("PersonId")
                        .HasColumnType("char(36)");

                    b.Property<sbyte>("Type")
                        .HasColumnType("tinyint")
                        .HasColumnName("Type");

                    b.HasKey("PersonId");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("IX_PersonType_PersonId");

                    b.ToTable("PersonType", (string)null);
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LastName");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_User_FullName");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.Person", b =>
                {
                    b.HasOne("RSoft.Person.Infra.Tables.User", "ChangedAuthor")
                        .WithMany("ChangedPersons")
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_User_Person_ChangedBy");

                    b.HasOne("RSoft.Person.Infra.Tables.User", "CreatedAuthor")
                        .WithMany("CreatedPersons")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_User_Person_CreatedBy");

                    b.Navigation("ChangedAuthor");

                    b.Navigation("CreatedAuthor");
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.PersonAddress", b =>
                {
                    b.HasOne("RSoft.Person.Infra.Tables.AddressType", "AddressType")
                        .WithMany("Addresses")
                        .HasForeignKey("AddressTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AddressType_PersonAddress_AddressTypeId");

                    b.HasOne("RSoft.Person.Infra.Tables.Person", "Person")
                        .WithMany("Addresses")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Person_PersonAddress_PersonId");

                    b.Navigation("AddressType");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.PersonPhone", b =>
                {
                    b.HasOne("RSoft.Person.Infra.Tables.Person", "Person")
                        .WithMany("Phones")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Person_PersonPhone_PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.PersonType", b =>
                {
                    b.HasOne("RSoft.Person.Infra.Tables.Person", "Person")
                        .WithMany("Types")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Person_PersonType_PersonId");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.AddressType", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.Person", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Phones");

                    b.Navigation("Types");
                });

            modelBuilder.Entity("RSoft.Person.Infra.Tables.User", b =>
                {
                    b.Navigation("ChangedPersons");

                    b.Navigation("CreatedPersons");
                });
#pragma warning restore 612, 618
        }
    }
}
